# Configuración del servidor
server.port=8080

# Conexión a PostgreSQL (Docker network)
spring.datasource.url=jdbc:postgresql://postgres-db:5432/clinica_db
spring.datasource.username=admin
spring.datasource.password=secretpassword

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect